language: clojure
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install $EVM_EMACS --skip --use
  - sudo apt-get install asciidoc source-highlight
  - cask
env:
  - EVM_EMACS=emacs-24.4-bin
script:
  - make test
notifications:
   email:
     - travis@russet.org.uk
     - jaydchan@gmail.com
  
